### ISSUE TITLE
Problems over one thousand

### ISSUE THREAD

**Issue by rdebath** [IAmWave/bfsieve#1]
If I replace your `,` instruction with the BF code below I can easily enter any number.

If I try `1010` I get `:09` rather than `1009` as a prime.
(If your interpreter has 8-bit cells you can use the [bitwidth conversions](https://esolangs.org/wiki/Brainfuck_bitwidth_conversions) to increase that, I suggest the no-copy variant)

``` brainfuck
+++++++++++[->++++++>++++++++++>+++++++++>+++<<<<]>+++.>.++++
++.>++.<--.>>-.<----.>.<<----.+++++++.--------.>+.+++.<+++++.
<-----------.>>>.[-]<[-]<[-]<[-]+[[-]>[-],[+[-----------[>[-]
++++++[-<------>]<--<<[->>++++++++++<<]>>[-<<+>>]<+>]]]<]<
```

**Comment by vvolhejn** [comment]
This is because the output code is made for 8-bit cells and, therefore, only three-digit numbers. Because this is the Brainfuck standard, I will leave it this way - the important part is the algorithm, not the output. I did implement your input code, though - thanks!
Here's a great interpreter, by the way: https://copy.sh/brainfuck/
